### ISSUE TITLE
`responseJSON` returns a Promise<Any>

### ISSUE THREAD

**Issue by sssilver** [PromiseKit/Alamofire-#15]
In core Alamofire, the fact that `responseJSON()` returns `Any` makes sense, because it can return both the proper JSON response, and any kind of a non-JSON value for error.

In PromiseKit/Alamofire, the non-JSON values can be returned as part of a rejected promise. Fulfilled promises can get a `[String: Any]` instead of `Any`.

**Comment by mxcl** [comment]
Correct me if wrong, but valid JSON can be any of:

* `Double`
* `[Any]`
* `[String: Any]`
* `Bool`
* `NSNull()`

We provide `responseJsonDictionary` because of this.

**Comment by sssilver** [comment]
There's no reason to use `NSNull()` instead of `nil`. There's no reason to not properly serialize optionals with `nil` value to a JSON null. If anything, it's the more intuitive approach, and dozens of confused developers on StackOverflow prove it.

This:
```
var x: String? = nil
let data = ["x": x]
```

Is more reasonable than this:
```
var x: String? = nil
let data = ["x": x ?? NSNull()]
```

**Comment by mxcl** [comment]
We don’t change anything that Alamofire gives us, and it doesn’t change anything that `NSJSONSerialization` gives it.

I'm all for providing more useful types, and that is why we provide `responseJsonDictionary` which returns what you are asking for.

However we cannot do this for the default `responseJSON` because, as stated, valid JSON is any of five types. Specifically the five types above, including `nil`, which comes through as `NSNull` I believe, and that's what Apple decide, not us.

It is not this framework’s goal to change Alamofire or `NSJSONSerialization`, it is our goal to provide promises for these things. However our other goal is convenience, so as well as `responseJSON` we provide `reponseJsonDictionary` which appears to be what you want.

**Comment by mxcl** [comment]
Closing due to lack of response.
